# Generated by Django 4.0.2 on 2022-05-09 22:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=90)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=16)),
                ('longtitude', models.DecimalField(decimal_places=15, max_digits=17)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricesqm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('link', models.CharField(max_length=255)),
                ('picture', models.CharField(max_length=255)),
                ('date_of_scraping', models.DateField(default=datetime.date.today)),
                ('location_data', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.locationdata')),
            ],
        ),
    ]
