# Generated by Django 4.0.2 on 2022-05-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdata',
            name='latitude',
            field=models.DecimalField(decimal_places=14, max_digits=16),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='longtitude',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pricesqm',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='offer',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
