FROM python:3.9.2

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . /app/

ENV PORT=8001

EXPOSE 8001

RUN ls

CMD ["python","manage.py","runserver","0.0.0.0:8001"]